version: '3.9'

services:
  tcpserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: node tcpserver.js
    container_name: tcp_server_container

  dbservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: node db.js
    container_name: db_service_container

  serverservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: node server.js
    container_name: server_service_container






